# Generated by Django 3.0.8 on 2022-04-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descripton',
            new_name='description',
        ),
    ]
